package com.distributed.mlp.gui;

import java.util.List;

import javafx.application.Platform;
import javafx.geometry.Insets;
import javafx.scene.Node;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ProgressBar;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.Spinner;
import javafx.scene.control.TitledPane;
import javafx.scene.control.Tooltip;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;

/**
 * Panel: Crash/fault-tolerance testing with WorkerReplacer.
 */
public class CrashTestPanel {

    private final LogConsole log;
    private volatile boolean testRunning = false;
    private Button stopButton;
    private Button scriptBtn;
    private Button progBtn;
    private ProgressBar progressBar;

    public CrashTestPanel(LogConsole log) { this.log = log; }

    public Node build() {
        ScrollPane scroll = new ScrollPane(buildContent());
        scroll.setFitToWidth(true);
        scroll.getStyleClass().add("panel-scroll");
        return scroll;
    }

    private Node buildContent() {
        VBox root = new VBox(20);
        root.getStyleClass().add("panel-content");
        root.setPadding(new Insets(28, 32, 28, 32));

        root.getChildren().add(panelHeader("💥 Crash & Fault Tolerance Testing",
            "Test worker crash detection, automatic replacement, and emergency checkpointing"));

        root.getChildren().add(buildHowItWorks());
        root.getChildren().add(buildCrashConfig());
        root.getChildren().add(buildCheckpointSection());

        return root;
    }

    private Node buildHowItWorks() {
        TitledPane tp = new TitledPane("How the Fault Tolerance System Works", null);
        tp.setCollapsible(true);
        tp.getStyleClass().add("config-section");

        VBox box = new VBox(10);
        box.setPadding(new Insets(14));

        String[] steps = {
            "1. Master watches each worker's gradient-push timestamps.",
            "2. If a worker goes silent for >60s (GRADIENT_TIMEOUT_MS), it's declared dead.",
            "3. WorkerReplacer queues the dead worker ID for respawn (only if -Dmlp.enableReplacer=true).",
            "4. A replacement Worker JVM is spawned (same ID, same shard seed) after 2s delay.",
            "5. Master's accept loop remains open, so replacements connect seamlessly.",
            "6. If ALL workers disconnect unexpectedly, Master writes an emergency checkpoint before exiting.",
            "7. On restart, the latest checkpoint is auto-loaded and training resumes.",
            "8. Max replacements per slot: 3. Only the 3 most recent checkpoints are kept.",
        };

        for (String s : steps) {
            Label l = new Label(s);
            l.getStyleClass().add("card-desc");
            box.getChildren().add(l);
        }

        tp.setContent(box);
        return tp;
    }

    private Node buildCrashConfig() {
        TitledPane tp = new TitledPane("Crash Test Configuration", null);
        tp.setCollapsible(false);
        tp.getStyleClass().add("config-section");

        GridPane grid = new GridPane();
        grid.setHgap(24); grid.setVgap(14);
        grid.setPadding(new Insets(16));

        Spinner<Integer> workersSpinner = intSpinner(2, 8, 3);
        Spinner<Integer> stepsSpinner   = intSpinner(10, 1000, 100);
        Spinner<Integer> portSpinner    = intSpinner(1024, 65535, 9001);
        Spinner<Integer> crashWorker    = intSpinner(0, 7, 1);
        Spinner<Integer> crashAfterSec  = intSpinner(5, 120, 15);
        Spinner<Integer> seedSpinner    = intSpinner(0, 99999, 42);

        addRow(grid, 0, "Total Workers",      workersSpinner, "Number of workers to launch initially");
        addRow(grid, 1, "Steps/Worker",       stepsSpinner,   "Training steps per worker (use ≥50 to give time for crash)");
        addRow(grid, 2, "Master Port",        portSpinner,    "TCP port for this test run");
        addRow(grid, 3, "Worker ID to Kill",  crashWorker,    "Which worker (0-indexed) gets killed mid-training");
        addRow(grid, 4, "Kill after (sec)",   crashAfterSec,  "Seconds after training start before killing the worker");
        addRow(grid, 5, "Seed",               seedSpinner,    "Random seed");

        Label warningLabel = new Label(
            "⚠ This test requires WorkerReplacer enabled via -Dmlp.enableReplacer=true\n" +
            "Uses run_with_worker_crashing.sh (generated by your project) OR the built-in " +
            "ProcessManager crash simulator below. The script approach is more realistic.");
        warningLabel.getStyleClass().add("bench-desc");
        warningLabel.setWrapText(true);

        progressBar = new ProgressBar(0);
        progressBar.setMaxWidth(Double.MAX_VALUE);
        progressBar.getStyleClass().add("training-progress");

        HBox btnRow = new HBox(12);

        // Script-based crash test
        scriptBtn = new Button("💥 Run via Shell Script");
        scriptBtn.getStyleClass().add("btn-danger");
        scriptBtn.setOnAction(e -> {
            if (testRunning) {
                log.append("⚠ A test is already running. Stop it first.");
                return;
            }
            
            int w  = workersSpinner.getValue();
            int s  = stepsSpinner.getValue();
            int p  = portSpinner.getValue();
            int cw = crashWorker.getValue();
            int ct = crashAfterSec.getValue();
            int seed = seedSpinner.getValue();

            if (cw >= w) {
                log.append("⚠ Worker ID to kill (" + cw + ") must be < total workers (" + w + ")");
                return;
            }

            startTest();
            log.clear();
            log.append("Running crash test script: run_with_worker_crashing.sh");
            log.append("Config: Workers=" + w + " Steps=" + s + " Kill=Worker" + cw + " After=" + ct + "s");

            ProcessManager.getInstance().launchScript(
                "run_with_worker_crashing.sh",
                List.of(String.valueOf(p), String.valueOf(w), String.valueOf(s),
                        String.valueOf(seed), String.valueOf(cw), String.valueOf(ct)),
                java.util.Map.of("MLP_ENABLE_WORKER_REPLACER", "true"),
                log.asConsumer(),
                code -> {
                    endTest(code == 0);
                    log.append(code == 0 ? "✅ Crash test complete." : "❌ Crash test ended (exit " + code + ")");
                }
            );
        });

        // Programmatic crash test
        progBtn = new Button("🔬 Simulate (Programmatic)");
        progBtn.getStyleClass().add("btn-primary");
        progBtn.setOnAction(e -> {
            if (testRunning) {
                log.append("⚠ A test is already running. Stop it first.");
                return;
            }
            
            int w  = workersSpinner.getValue();
            int s  = stepsSpinner.getValue();
            int p  = portSpinner.getValue();
            int cw = crashWorker.getValue();
            int ct = crashAfterSec.getValue();
            int seed = seedSpinner.getValue();

            if (cw >= w) {
                log.append("⚠ Worker ID to kill (" + cw + ") must be < total workers (" + w + ")");
                return;
            }

            startTest();
            log.clear();
            log.append("🚀 Starting distributed training with crash simulation...");
            log.append("Workers: " + w + " | Steps: " + s + " | Kill worker " + cw + " after " + ct + "s");
            log.append("Note: WorkerReplacer must be enabled (-Dmlp.enableReplacer=true)");

            ProcessManager.getInstance().launchDistributedWithCrash(p, w, s, seed, cw, ct,
                log.asConsumer(),
                success -> {
                    endTest(success);
                    log.append(success
                        ? "✅ Crash test complete — check logs/ for replacement activity."
                        : "⚠ Training ended (may have saved emergency checkpoint).");
                });
        });

        // Stop button
        stopButton = new Button("⏹ STOP Test");
        stopButton.getStyleClass().add("btn-stop");
        stopButton.setDisable(true);
        stopButton.setOnAction(e -> {
            if (!testRunning) return;
            
            log.append("⏹ Stopping test by user request...");
            ProcessManager.getInstance().stopAllProcesses();
            
            // Force stop after 2 seconds if processes don't terminate
            new Thread(() -> {
                try {
                    Thread.sleep(2000);
                    if (testRunning) {
                        Platform.runLater(() -> {
                            endTest(false);
                            log.append("⚠ Test forcefully terminated.");
                        });
                    }
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                }
            }).start();
        });

        btnRow.getChildren().addAll(scriptBtn, progBtn, stopButton);

        VBox box = new VBox(14, grid, warningLabel, btnRow, progressBar);
        box.setPadding(new Insets(14));
        tp.setContent(box);
        return tp;
    }

    private Node buildCheckpointSection() {
        TitledPane tp = new TitledPane("Checkpoint Management", null);
        tp.setCollapsible(false);
        tp.getStyleClass().add("config-section");

        Label desc = new Label(
            "Master saves a checkpoint every 5 gradient updates (atomic rename).\n" +
            "At most 3 checkpoints are kept: checkpoint_0.bin, checkpoint_5.bin, checkpoint_10.bin, ...\n" +
            "On restart, the latest checkpoint is auto-restored (update counter + weights).\n" +
            "Emergency checkpoint is written if all workers disconnect unexpectedly.");
        desc.getStyleClass().add("bench-desc");
        desc.setWrapText(true);

        Button listBtn = new Button("📂 List Checkpoints");
        listBtn.getStyleClass().add("btn-outline");
        listBtn.setOnAction(e -> {
            java.io.File resultsDir = ProcessManager.projectRoot().resolve("results").toFile();
            if (!resultsDir.exists()) { log.append("No results/ directory found."); return; }
            log.append("=== Checkpoints in results/ ===");
            java.io.File[] files = resultsDir.listFiles((d, n) -> n.startsWith("checkpoint_") || n.startsWith("model_weights_"));
            if (files == null || files.length == 0) { log.append("  (none found)"); return; }
            java.util.Arrays.sort(files);
            for (java.io.File f : files) {
                long kb = f.length() / 1024;
                log.append("  " + f.getName() + "  (" + kb + " KB)  modified: " + new java.util.Date(f.lastModified()));
            }
        });

        Button clearBtn = new Button("🗑 Clear Checkpoints");
        clearBtn.getStyleClass().add("btn-outline");
        clearBtn.setOnAction(e -> {
            java.io.File resultsDir = ProcessManager.projectRoot().resolve("results").toFile();
            if (!resultsDir.exists()) { log.append("No results/ directory found."); return; }
            java.io.File[] files = resultsDir.listFiles((d, n) -> n.startsWith("checkpoint_"));
            if (files == null || files.length == 0) { log.append("No checkpoints to clear."); return; }
            int count = 0;
            for (java.io.File f : files) {
                if (f.delete()) count++;
            }
            log.append("Cleared " + count + " checkpoint(s).");
        });

        HBox btnBox = new HBox(12, listBtn, clearBtn);

        VBox box = new VBox(12, desc, btnBox);
        box.setPadding(new Insets(14));
        tp.setContent(box);
        return tp;
    }

    // ── Test lifecycle management ────────────────────────────────────────

    private void startTest() {
        testRunning = true;
        Platform.runLater(() -> {
            scriptBtn.setDisable(true);
            progBtn.setDisable(true);
            stopButton.setDisable(false);
            progressBar.setProgress(-1); // Indeterminate
        });
    }

    private void endTest(boolean success) {
        testRunning = false;
        Platform.runLater(() -> {
            scriptBtn.setDisable(false);
            progBtn.setDisable(false);
            stopButton.setDisable(true);
            progressBar.setProgress(success ? 1.0 : 0.0);
        });
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static void addRow(GridPane g, int row, String label, Node ctrl, String tip) {
        Label lbl = new Label(label); lbl.getStyleClass().add("config-label");
        Tooltip.install(ctrl, new Tooltip(tip));
        g.add(lbl, 0, row); g.add(ctrl, 1, row);
    }

    private static Spinner<Integer> intSpinner(int min, int max, int def) {
        Spinner<Integer> s = new Spinner<>(min, max, def);
        s.setEditable(true); s.setPrefWidth(110);
        return s;
    }

    private static Node panelHeader(String title, String subtitle) {
        VBox box = new VBox(4);
        Label t = new Label(title); t.getStyleClass().add("panel-title");
        Label s = new Label(subtitle); s.getStyleClass().add("panel-subtitle");
        box.getChildren().addAll(t, s);
        return box;
    }
}